- alias: "Actualizar Consumo Diario XC40"
  trigger:
    - platform: time
      at: "23:59:00"
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.consumo_bateria_xc40_dia
      data:
        value: "{{ states('sensor.consumo_bateria_xc40') | float }}"
  mode: single

- alias: "Actualizar Consumo Diario V90"
  trigger:
    - platform: time
      at: "23:59:00"
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.consumo_diesel_v90_dia
      data:
        value: "{{ states('sensor.consumo_diesel_v90') | float }}"
  mode: single
  
  
- alias: Forzar lectura de temperatura
  trigger:
    - platform: time_pattern
      minutes: "/10"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: climate.bano_principal
        
- alias: Forzar lectura de temperatura
  trigger:
    - platform: time_pattern
      minutes: "/10"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: climate.hab_ainara        
        
- alias: Forzar lectura de temperatura
  trigger:
    - platform: time_pattern
      minutes: "/10"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: climate.hab_hugo       
        
        